library(dplyr)
library(ggplot2)

beijing_2008 <- read.csv("Beijing_2008_HourlyPM2.5_created20140325.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2009 <- read.csv("Beijing_2009_HourlyPM25_created20140709.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2010 <- read.csv("Beijing_2010_HourlyPM25_created20140709.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2011 <- read.csv("Beijing_2011_HourlyPM25_created20140709.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2012 <- read.csv("Beijing_2012_HourlyPM2.5_created20140325.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2013 <- read.csv("Beijing_2013_HourlyPM2.5_created20140325.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2014 <- read.csv("Beijing_2014_HourlyPM25_created20150203.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2015 <- read.csv("Beijing_2015_HourlyPM25_created20160201.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_2016 <- read.csv("Beijing_2016_HourlyPM25_created20170103.csv",
                         header = TRUE,
                         skip = 3,
                         colClasses = c("character",
                                        "character", 
                                        "character", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "integer", 
                                        "character", 
                                        "character", 
                                        "character"))
beijing_air <- rbind(beijing_2008, 
                     beijing_2009,
                     beijing_2010,
                     beijing_2011,
                     beijing_2012,
                     beijing_2013,
                     beijing_2014,
                     beijing_2015,
                     beijing_2016)
beijing_air$Value[beijing_air$Value==-999] <- NA
avg_air <- summarise(group_by(beijing_air, Year, Month, Day), avgValue = round(mean(Value, na.rm = TRUE)))
avg_air$pollution <- cut(avg_air$avgValue, c(0,50, 100, 150, 200, 300, 1000))
levels(avg_air$pollution) <- c("Excellent",
                               "Good",
                               "Lightly Polluted",
                               "Moderately Polluted",
                               "Heavily Polluted",
                               "Severely Polluted")
pollcolor <- c("green", "yellow", "orange", "red", "maroon", "red4", "gray")